FROM python:3.12-slim

WORKDIR /app/main

COPY Main/text-puzzles-backend/requirements.txt ./

#frontend stage
FROM node:22.0.0-slim AS frontend-builder
WORKDIR /app/main/frontend
COPY Main/text-puzzles-frontend ./
RUN npm install
RUN npm run build

#backend stage
FROM python:3.12-slim
WORKDIR /app/main
COPY --from=frontend-builder /app/main/frontend/dist ./static
COPY Main/text-puzzles-backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY Main/text-puzzles-backend ./

#https
EXPOSE 443


# Run the main server script
CMD ["python", "server.py"]