FROM python:3.12-slim

WORKDIR /app/game

COPY Game/text-puzzles-game/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY Game/text-puzzles-game ./

EXPOSE 41801

# Run the game server script
CMD ["python", "server.py"]